// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgiltpmfufrmuzcyddjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnaWx0cG1mdWZybXV6Y3lkZGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTk1NDYsImV4cCI6MjA2Njg3NTU0Nn0.Ya2SgOrjsDoMvFofZec0tp67SWnH5Rx7ge1AgQ2aa6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});